{{- if .Values.storageClass.enabled }}
{{- if .Values.storageClass.immediate.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.immediate.name }}
  {{- if .Values.storageClass.immediate.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  labels:
    {{- include "kloud-csi.labels" . | nindent 4 }}
provisioner: {{ .Values.driver.name }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: Immediate
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- with .Values.storageClass.immediate.parameters }}
parameters:
  {{- range $key, $value := . }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .Values.storageClass.immediate.enabled .Values.storageClass.waitForFirstConsumer.enabled }}
---
{{- end }}
{{- if .Values.storageClass.waitForFirstConsumer.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.waitForFirstConsumer.name }}
  {{- if .Values.storageClass.waitForFirstConsumer.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  labels:
    {{- include "kloud-csi.labels" . | nindent 4 }}
provisioner: {{ .Values.driver.name }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- with .Values.storageClass.waitForFirstConsumer.parameters }}
parameters:
  {{- range $key, $value := . }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
